### ISSUE TITLE
DistModel

### ISSUE THREAD

**Issue by Ricelll** [yiranran/QMUPD#1]
excuse me, I can't find DistModel in cycle_gan_cls_model.py. Could u help me?

<img width="590" alt="截屏2022-03-22下午3 57 26" src="https://user-images.githubusercontent.com/31204531/159433914-b54dadd8-5fcd-4b62-a8c5-440dc3d6b63e.png">

**Comment by Ricelll** [comment]
`import models.dist_model as dm` in Line6

**Comment by AnimatePortrait** [comment]
Sorry for late reply. I added the missing files. [https://github.com/yiranran/QMUPD/commit/de277def28c44a15ba14a86cb7c817318cd65f65](commit #4)

**Comment by yiranran** [comment]
Sorry for late reply. I added the missing files. [https://github.com/yiranran/QMUPD/commit/de277def28c44a15ba14a86cb7c817318cd65f65](commit #4)

**Comment by yiranran** [comment]
Sorry for the late reply. I added the missing files in the latest commit. [commit #4](https://github.com/yiranran/QMUPD/commit/de277def28c44a15ba14a86cb7c817318cd65f65)
